services:
  - type: web
    name: speech-emotion-recognition
    env: python
    rootDir: CS-FAIR-DEMO
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 1 --threads 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.19
      - key: NUMBA_DISABLE_JIT
        value: "0"
    healthCheckPath: /

